### ISSUE TITLE
Two More Variable Colours

### ISSUE THREAD

**Issue by ManUtdNZ** [gpaulissen/bml#1]
Hi
Really enjoying your development of BML as I see it has a lot of benefits for Bridge Partnerships to write up their systems in both HTML and PDF form via LaTex.

Can you create two more "colours": Y & Z where X<Y<Z so that a jump (1X-2Y) or a 2/1 1Y-2X sequence can be described?

**Comment by gpaulissen** [comment]
Solved in next release (2.2.0).

**Comment by gpaulissen** [comment]
Solved in next release (2.2.0).

**Comment by ManUtdNZ** [comment]
Excellent. Well done.

________________________________
