### ISSUE TITLE
Puzzling indentation error

### ISSUE THREAD

**Issue by gpaulissen** [gpaulissen/bml#12]
This BML looks right but there is an error anyhow.

BML (see attachment):

```
(1N)---
  D 4M, 5+m
    2C P|C eg1 4324: P 2D eg2 3613: Correct 2D to 2H, NF 
    2D P|C; shortage in C eg [3451](url)
    2H P|C: no S|V in either minor; could be (43) in M
    2S P|C to minor
    2N GF INQ
      3C = H + C

```
Error:

`IndentationError: Indentation (6) must be the level of its parent (2) mutiplied by the indentation argument (2)`
[MLP.zip](https://github.com/gpaulissen/bml/files/6440630/MLP.zip)

**Comment by gpaulissen** [comment]
I know what is wrong. The description of the double aligns with the bids underneath. BML assumes that those (2C thru 2N) are part of the description of the double. And then the next bid 3C has a wrong indentation. Solution is to use an equal sign after any bid, at least the double. Problem solved, nevertheless I will try to enhance the feedback.

**Comment by ManUtdNZ** [comment]
Excellent. I will change my writing style to accommodate this.

Brian

**Comment by gpaulissen** [comment]
In release 2.6.0 the bids and descriptions scanned will be displayed when the verbosity is at least 1.
