### ISSUE TITLE
Log File

### ISSUE THREAD

**Issue by ManUtdNZ** [gpaulissen/bml#13]
Hi
Not an issue just a suggestion.

The only time I have to use the command line is when I'm troubleshooting and the text file, error messages and a likely location for the troublesome line appears. Is it possible to have a log file created instead/as well please with this information?

Otherwise all going well. Keep up the excellent work.

Brian

**Comment by gpaulissen** [comment]
You can use a command line with the -v (verbose option) like this:

bml2htm -v YOUR.bml 2>YOUR.log

and even more more verbose:

bml2htm -v -v YOUR.bml 2>YOUR.log

The 2> YOUR.log redirects standard error (where the logging goes) into a file

If you just want to have a look and not logging to file:

bml2htm -v YOUR.bml
