### ISSUE TITLE
Bold doesn't work in bml2latex

### ISSUE THREAD

**Issue by ManUtdNZ** [gpaulissen/bml#14]
Hi
You have fixed the * issue in bml2html. For example:

4C *Gerber - 1430*

Works just fine. Gerber - 1430 appears Bold. However, when I use bml2latex, the line is interpreted verbatim ie what you see above is what you get. The * doesn't get interpreted as "turn on Bold". Does that make sense?

Brian

**Comment by gpaulissen** [comment]
The parser need some whitespace before the first * which caused a problem when there was no character at all in the generated LaTeX file before the first *. That has been solved by just ignoring expressions with a non whitespace character, a so called negative lookbehind assertion.

**Comment by gpaulissen** [comment]
Solved in 2.7.0
