### ISSUE TITLE
Bold doesn't work

### ISSUE THREAD

**Issue by ManUtdNZ** [gpaulissen/bml#15]
Hi
I've attached a bml as as a txt file. If you create a htm and a pdf, you will see that the *Bold* works in the htm conversion but not when creating a pdf in certain circumstances.

Hope this helps solve the problem.

Brian
[1N-reduced.txt](https://github.com/gpaulissen/bml/files/6787615/1N-reduced.txt)

**Comment by gpaulissen** [comment]
See https://github.com/gpaulissen/bml/issues/14
