### ISSUE TITLE
Opener's Rebid

### ISSUE THREAD

**Issue by ManUtdNZ** [gpaulissen/bml#2]
I was trying to get opener's rebids listed neatly with something like:

2C-(2X)-P-(P);
D Balanced, cooperative T/O
2N Stoppers

When I converted using BML2html, I got:
![image](https://user-images.githubusercontent.com/79065040/112052820-6e8e6080-8bb8-11eb-91f0-2fc9c5601ac1.png)

The formatting just isn't as nice as it could be. Is it worth you investing your time trying to sort this?

**Comment by ManUtdNZ** [comment]
Hi
Not sure if this helps, but I notice I get the required effect when I convert with the --tree parameter:

![image](https://user-images.githubusercontent.com/79065040/112062112-53295280-8bc4-11eb-9b8f-c0c31afc6036.png)

**Comment by gpaulissen** [comment]
Is this okay (you reopened it)? 
Seems okay to me (just have to use the --tree option which is default).

**Comment by ManUtdNZ** [comment]
Sure.

Thanks

________________________________

**Comment by gpaulissen** [comment]
Solved.
