### ISSUE TITLE
Blank & Comment Line

### ISSUE THREAD

**Issue by ManUtdNZ** [gpaulissen/bml#7]
Hi
This is just a long term suggestion not any grumble.

I create a blank line by inserting the description line with just a full stop. Barely notice the dot and the white space helps readability.

In regard to a Comment line, your notes say it isn't possible to place such except in the manner I've used above. Maybe, when you have time, this could be incorporated. Perhaps, a \\ could signify such. Would need the spacing on the line left as typed.

Simply a thought.
[Blank line.txt](https://github.com/gpaulissen/bml/files/6201182/Blank.line.txt)

**Comment by gpaulissen** [comment]
Hi,

So if I understand you correctly you would like a blank line below 1N-2C-2D-P and 1N-2C-2D-2H-2S-4CD in the generated files? And to have that you need to insert a line with a dot at the end?

**Comment by ManUtdNZ** [comment]
Hi
Yes. I use white space to make the material easier to compartmentalise the material otherwise it is just a river of text that is hard to come to terms wth.

Hope that makes it clearer.

The comment reference again is a need I’ve had occasionally to describe an upcoming bidding table.

Brian

Sent from my iPad

On 26/03/2021, at 6:38 AM, Gert-Jan Paulissen ***@***.******@***.***>> wrote:


Hi,

So if I understand you correctly you would like a blank line below 1N-2C-2D-P and 1N-2C-2D-2H-2S-4CD in the generated files? And to have that you need to insert a line with a dot at the end?

**Comment by gpaulissen** [comment]
For the time being an empty line is not allowed, but maybe it should.

**Comment by gpaulissen** [comment]
A bidding table line with a single point (anywhere) will be ignored as in the attachment. You can even just start a line with a point.

**Comment by ManUtdNZ** [comment]
Hi
I think you might have misunderstood my comment on whitespace. Prior to this update, I could have a single line with a dot [ in the comment position ] which created a blank line [ white space ] showing in both the html & latex outputs as I wanted. It appears now that the line only shows in the bml file and not in html & latex files. The line with a dot is factored out.

Does that make sense?

**Comment by gpaulissen** [comment]
A line with a single dot in a bidding table will translate into an empty line.

**Comment by gpaulissen** [comment]
Solved in release 2.6.1
